//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastebookEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PB_FRIEND
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public int FRIEND_ID { get; set; }
        public string REQUEST { get; set; }
        public string BLOCKED { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
    
        public virtual PB_USER PB_USER { get; set; }
        public virtual PB_USER PB_USER1 { get; set; }
        public virtual PB_USER PB_USER2 { get; set; }
    }
}
